// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: places.sql

package database

import (
	"context"
	"encoding/json"
)

const createPlace = `-- name: CreatePlace :one
INSERT INTO places (id, place_name, country, city, category, place_detail,created_at, updated_at)
VALUES(
gen_random_uuid(),  
$1,
$2,
$3,
$4,
$5,
NOW(),
NOW()
)
RETURNING id, place_name, country, city, category, place_detail, created_at, updated_at
`

type CreatePlaceParams struct {
	PlaceName   string
	Country     string
	City        string
	Category    string
	PlaceDetail json.RawMessage
}

func (q *Queries) CreatePlace(ctx context.Context, arg CreatePlaceParams) (Place, error) {
	row := q.db.QueryRowContext(ctx, createPlace,
		arg.PlaceName,
		arg.Country,
		arg.City,
		arg.Category,
		arg.PlaceDetail,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.PlaceName,
		&i.Country,
		&i.City,
		&i.Category,
		&i.PlaceDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
