// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type CitiesImage struct {
	ID        uuid.UUID
	CountryID uuid.UUID
	Country   string
	City      string
	CityImage string
	CreatedAt time.Time
}

type CountriesImage struct {
	ID           uuid.UUID
	Country      string
	CountryImage string
	CreatedAt    time.Time
}

type Place struct {
	ID          string
	PlaceName   string
	Country     string
	City        string
	Category    string
	PlaceDetail json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID             uuid.UUID
	Username       string
	ImagePublicID  string
	ImageSecureUrl string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}

type UsersBookmark struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Username  string
	PlaceID   string
	PlaceName string
	Catagory  string
	PlaceText string
	CreatedAt time.Time
}

type UsersPasswordReset struct {
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiredAt time.Time
	ResetKey  uuid.UUID
}
