// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: places.sql

package database

import (
	"context"
	"encoding/json"
)

const createPlace = `-- name: CreatePlace :one
INSERT INTO places (id, place_name, country, city, category, place_detail,created_at, updated_at)
VALUES(
$1,  
$2,
$3,
$4,
$5,
$6,
NOW(),
NOW()
)
On CONFLICT (id, place_name,country, city)
DO NOTHING
RETURNING id, place_name, country, city, category, place_detail, created_at, updated_at
`

type CreatePlaceParams struct {
	ID          string
	PlaceName   string
	Country     string
	City        string
	Category    string
	PlaceDetail json.RawMessage
}

func (q *Queries) CreatePlace(ctx context.Context, arg CreatePlaceParams) (Place, error) {
	row := q.db.QueryRowContext(ctx, createPlace,
		arg.ID,
		arg.PlaceName,
		arg.Country,
		arg.City,
		arg.Category,
		arg.PlaceDetail,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.PlaceName,
		&i.Country,
		&i.City,
		&i.Category,
		&i.PlaceDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlace = `-- name: GetPlace :one
SELECT id, place_name, country, city, category, place_detail, created_at, updated_at FROM places WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlace(ctx context.Context, id string) (Place, error) {
	row := q.db.QueryRowContext(ctx, getPlace, id)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.PlaceName,
		&i.Country,
		&i.City,
		&i.Category,
		&i.PlaceDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaceIDFromDB = `-- name: GetPlaceIDFromDB :one
SELECT id FROM places WHERE place_name = $1 LIMIT 1
`

func (q *Queries) GetPlaceIDFromDB(ctx context.Context, placeName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPlaceIDFromDB, placeName)
	var id string
	err := row.Scan(&id)
	return id, err
}
