name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Run tests
        run: cd src && go test -cover ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Check formatting
        run: cd src && test -z $(go fmt ./...)

      - name: Install staticcheck (linting checks)
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check staticcheck for linting
        run: cd src && staticcheck ./...

      - name: Install gosec (security checks)
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Security checks
        run: cd src && gosec ./...
