name: ci

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Format check
        run: cd discovery-api && test -z $(go fmt ./...)


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Build
        run: ./scripts/build.sh


  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Install staticcheck (static analysis)
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run static analysis
        run: cd discovery-api && staticcheck ./...

      - name: Install gosec (security checks)
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run security analysis
        run: cd discovery-api && gosec -exclude-dir=internal ./...
